export const movies = [
  {
    slug: 'lady-bird',
    title: 'LADY BIRD',
    director: 'Greta Gerwig',
    genres: ['Thriller', 'Drama'],
    description:
      'A fiercely independent teenager tries to make her own way in the world while wanting to get out of her hometown of Sacramento, California and to get away from her complicated mother and recently-unemployed father.',
    location: 'Los Angeles, California | Film short',
    image: '/images/lady-bird.png',
    video: 'https://www.youtube.com/watch?v=cNi_HC839Wo',
    chainId: 1315,
    listingId: '1',
    deadline: '32d 18h',
    deadlineDate: '2025 October 16',
    fundedGoal: 9000,
    funded: 7500,
  },
  {
    slug: 'matrix',
    title: 'MATRIX',
    director: 'Keanu Reeves',
    genres: ['Thriller', 'Drama'],
    description:
      'A fiercely independent teenager tries to make her own way in the world while wanting to get out of her hometown of Sacramento, California and to get away from her complicated mother and recently-unemployed father.',
    location: 'Los Angeles, California | Film short',
    image: '/images/matrix.png',
    video: 'https://www.youtube.com/watch?v=cNi_HC839Wo',
    chainId: 1315,
    listingId: '1',
    deadline: '15d 4h',
    deadlineDate: '2025 October 16',
    fundedGoal: 15000,
    funded: 8000,
  },
  {
    slug: 'pulp-ficton',
    title: 'PULP FICTION',
    director: 'Quentin Tarantino',
    genres: ['Thriller', 'Drama'],
    description:
      'A fiercely independent teenager tries to make her own way in the world while wanting to get out of her hometown of Sacramento, California and to get away from her complicated mother and recently-unemployed father.',
    location: 'Los Angeles, California | Film short',
    image: '/images/pulp-fiction.png',
    video: 'https://www.youtube.com/watch?v=cNi_HC839Wo',
    chainId: 1315,
    listingId: '1',
    deadline: '20d 19h',
    deadlineDate: '2025 October 16',
    fundedGoal: 30000,
    funded: 21000,
  },
]
